# Generated by Django 5.1.7 on 2025-03-28 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='xpentry',
            old_name='xp_points',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='xpentry',
            name='activity',
        ),
        migrations.AddField(
            model_name='xpentry',
            name='category',
            field=models.CharField(choices=[('Pushups', 'Pushups'), ('Running', 'Running'), ('Meditation', 'Meditation'), ('Breathwork', 'Breathwork'), ('Custom', 'Custom')], default='Custom', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xpentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('rank', models.CharField(default='Unranked', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
